# Alur Student Sign Up Academy

Setiap student memiliki beberapa administrasi yang perlu diketahui dan diikuti selama mengikuti kelas Algoritma Academy.

## Pengajuan Mentoring

Mentoring merupakan salah satu fasilitas yang diterima oleh student Algoritma berupa sesi 101 dengan mentor Algoritma untuk menanyakan hal-hal yang belum dipahami dan ingin dipelajari lebih lanjut. Berikut ini beberapa peraturan yang berhubungan dengan mentoring:

1. Mentoring dilaksanakan **1x/minggu** dengan durasi 1 jam pada hari kerja Senin-Jumat pukul 10:00-18:00.
2. Pengajuan mentoring terpusat melalui email [mentor@algorit.ma](mentor@algorit.ma).
3. Permintaan mentoring dilakukan **maksimal H-1 sebelum hari mentoring** yang diinginkan pada hari Senin-Jumat pukul 10:00-18:00 WIB, dengan template permintaan mentoring sebagai berikut:

```
Berikan subject email : ALGORITMA MENTORING SESSION
Nama : ___________
Kelas : ___________ (nama batch day / night)
Materi mentoring : ___________
Tanggal, Jam mentoring : ___________
```
4. Permintaan mentoring yang diajukan melewati jam kerja akan dibalas pada hari berikutnya dan pelaksanaan mentoring tidak dapat dilakukan pada hari yang sama.
5. Pengajuan mentoring yang tidak sesuai dengan template yang ada maka akan dikembalikan kepada student kembali hingga informasi pada template mentoring sudah terpenuhi. Apabila informasi pada template telah terpenuhi, mentoring baru akan diproses.
6. Apabila terdapat lebih dari satu permintaan mentoring dengan waktu serta materi yang sama, maka admin dapat menawarkan untuk dilakukan secara bersamaan dengan mentor yang sama.
7. Student tidak diperkenankan untuk memilih mentor untuk membantunya selama mentoring.

## Pengajuan Pertanyaan

1. Setiap student yang mengalami kesulitan dalam proses belajar memiliki hak untuk bertanya diluar kelas baik secara langsung maupun melalui email.
2. Pengajuan pertanyaan diluar kelas melalui email terpusat melalui email [mentor@algorit.ma](mentor@algorit.ma).
3. Tidak diperkenankan bagi tim Sales memberikan nomor handphone kepada student.
4. Pengajuan pertanyaan yang baik dan benar sesuai dengan dokumentasi berikut : [How to ask question](https://drive.google.com/file/d/1gWSTNF3wXK5Lbfssb-eT_A3gbnLvY_ez/view)[^1]

## Pengajuan Pindah Kelas

Student yang memiliki kendala dalam mengikuti kelas sesuai jadwal yang telah diikuti dapat mengajukan pindah kelas. Adapun syarat pengajuan pindah kelas adalah sebagai berikut:

1. Student melakukan pengajuan pindah kelas **maksimal H-2 (pada hari kerja)** sebelum jadwal perpindahan kelas yang diajukan melalui email [mentor@algorit.ma](mentor@algorit.ma).
2. Pengajuan pindah kelas hanya bisa dilakukan **1 *course* penuh**.
3. Setelah pengajuan pindah kelas disetujui, teaching assistant yang bertugas pada course tersebut **wajib** memberikan undangan kepada student untuk masuk ke dalam google classroom kelas yang akan diikuti.
4. Student yang telah bergabung pada google classroom yang baru berhak untuk:

* mendapatkan material utama dan inclass material selama *course* tersebut
* mendapatkan link kelas dan recording kelas (apabila student tersebut mengikuti kelas online)
* mendapatkan soal latihan atau pekerjaan rumah (PR) yang harus dikerjakan selama *course* berlangsung
5. Student yang melakukan perpindahakan kelas tetap **memgumpulkan quiz dan learn by building (LBB) pada google classroom mandatory (utama)** bukan pada google classroom selama perpindahan kelas.
6. Apabila *course* yang dilakukan pindah kelas telah selesai, maka teaching assistant wajib menghapus student tersebut dari google classroom sementaranya H+7 (termasuk hari libur) setelah *course* berakhir.

## Sertifikat

### Jenis Sertifikat

1. Sertifikat diberikan kepada student yang mengikuti kelas Algoritma Academy baik dalam bentuk kelas per spesialisasi, Academy Reguler, maupun Academy Full Stack baik secara onsite maupun online.
2. Sertifikat yang diberikan terdapat tiga jenis sertifikat:

* [sertifikat per course](https://drive.google.com/file/d/1r_nST2hqB02afh3cMV1EypkxDvGab6WV/view?usp=sharing)
* [sertifikat specialization](https://drive.google.com/file/d/1m9CuUjAnWCspSyKGSmvmPc7eabCg_KWS/view?usp=sharing)
* [rubrik dari seluruh course](https://drive.google.com/file/d/11joZCgOGWZqxQTAjVaOMNy9ct1U4h5-P/view?usp=sharing)


### Pemberian Sertifikat

1. Sertifikat per course akan dikirimkan **setiap hari Jumat** setelah course berakhir yang dapat diakses melalui google classroom.
2. Sertifikat specialization serta rubrik dalam bentuk *softcopy* akan diberikan dalam waktu **2 minggu setelah deadline pengumpulan capstone** pada masing-masing spesialisasi yang diambil melalui email.
3. Student yang diperbolehkan meminta sertifikat specialization dan rubriks dalam bentuk *hardcopy* hanya yang mengikuti kelas secara onsite.  
4. Student yang menginginkan sertifikat specialization dalam bentuk *hardcopy* dapat mengajukan melalui link GForm berikut [http://bit.ly/request-certificate](http://bit.ly/request-certificate) yang akan disampaikan melalui classroom.

## Letter of Recommendation (LoR)

*Letter of recommendation* merupakan surat rekomendasi yang diberikan oleh pihak Algoritma kepada student yang memiliki  nilai minimal 90% yang dapat digunakan surat pendamping dalam melamar pekerjaan. Berikut syarat student yang dapat mendapatkan LoR:

1. Student yang mengikuti kelas  Academy Full Stack atau Academy Reguler secara onsite. 
2. Memiliki nilai minimal 90% dari total nilai spesialisasi.
3. Untuk mendapatkan LoR, student harus mengajukan pembuatan LoR melalui email [mentor@algorit.ma](mentor@algorit.ma) dengan memberikan informasi:

* Nama
* Nomor Induk Kependudukan (NIK)
* Alamat sesuai KTP

## Fasilitas Setelah Kelas

Algoritma menyediakan *lifetime learning* yang bisa dimanfaatkan oleh student setelah menyelesaikan Algoritma Academy. Fasilitas yang diberikan kepada student dibedakan berdasarkan jenis kelas yang diambil yaitu secara onsite atau online.

### Academy Onsite Full Stack / Reguler

1. Mendapatkan fasilitas mentoring selama 4 minggu setelah Capstone Project Machine Learning.
2. Diundang pada forum diskusi alumni Algoritma menggunakan platform Slack. 
3. Mendapatkan fasilitas career support berupa project show case dalam event Data Career Day (DCD) dan pembuatan curriculum vitae (CV) yang akan dikirimkan kepada *hiring partner* Algoritma.
4. Gratis mengikuti beberapa workshop yang diselenggarakan oleh Algoritma tanpa batasan waktu dengan limit biaya workshop sebesar 35 juta.

### Academy Online Full Stack / Reguler

1. Mendapatkan fasilitas mentoring selama 4 minggu setelah Capstone Project Machine Learning.
2. Diundang pada forum diskusi alumni Algoritma menggunakan platform Slack. 
3. Mendapatkan fasilitas career support berupa pembuatan curriculum vitae (CV) yang akan dikirimkan kepada *hiring partner* Algoritma.

