# Academy for Dummies

Berikut beberapa hal yang perlu dipersiapkan selama bertugas di kelas Algoritma Academy `r emo::ji("smile")`.

## Persiapan Academy

### Sebelum Kelas

#### Kelas Onsite

* Mengirimkan postingan yang berisi informasi kelas sesuai dengan template [berikut](https://docs.google.com/document/d/1leWbp3Eb2AwumFieuHiWStSNOXsKJQJD_h0tAhA2fLs/edit#) H-1 pada hari kerja sebelum kelas dimulai pada google classroom.
* Mengirimkan course material H-1 pada hari kerja sebelum kelas dimulai pada google classroom. Link drive material dapat diakses pada [link berikut](https://drive.google.com/drive/folders/1I1h0p4BkvkUYV8mtDU7bgswE_awOIxWY?usp=sharing).
* Mengirimkan informasi mengenai kelas hanya pada student yang terdapat pada kelas tersebut sesuai dengan informasi pada sheet [active student](https://docs.google.com/spreadsheets/d/12FB9410fhRhZp9jl5qLe7x-LGw0QTSfLujA-dE867JE/edit#gid=115188088).
* Melakukan briefing dengan teaching team yang bertugas.

#### Kelas Online

* Mempersiapkan link zoom meeting, [Online Class Guide](https://docs.google.com/document/d/16algZSEqLos2fksPcbmpUrpvvuVr62msVY13M8uPNos/edit#), [Error Issues](https://docs.google.com/document/d/1ZkhuxSTBjUqzbHeLsRbk8E4L1FFymWH0UmaI3xaomkg/edit#), dan link absensi H-1 pada hari kerja sebelum kelas dimulai 
* Mengirimkan postingan yang berisi informasi kelas sesuai dengan template [berikut](https://docs.google.com/document/d/1leWbp3Eb2AwumFieuHiWStSNOXsKJQJD_h0tAhA2fLs/edit#) H-1 pada hari kerja sebelum kelas dimulai pada google classroom.
* Mengirimkan course material H-1 pada hari kerja sebelum kelas dimulai pada google classroom. Link drive material dapat diakses pada [link berikut](https://drive.google.com/drive/folders/1I1h0p4BkvkUYV8mtDU7bgswE_awOIxWY?usp=sharing)
* Mengirimkan informasi mengenai kelas hanya pada student yang terdapat pada kelas tersebut sesuai dengan informasi pada sheet [active student](https://docs.google.com/spreadsheets/d/12FB9410fhRhZp9jl5qLe7x-LGw0QTSfLujA-dE867JE/edit#gid=115188088)
* Melakukan briefing dengan teaching team yang bertugas.

> Bagi yang bertugas online dan merasa membutuhkan kamera, mic, dan wacom dapat menghubungi operation. Selain itu yang merasa koneksi internet tidak stabil, dapat datang ke kantor agar kelas berjalan dengan baik.

### Saat Kelas

#### Kelas Onsite

* Melakukan pengecekan papan tulis, spidol, dan projector dapat berjalan dengan baik.
* Mengadakan sesi QnA selama 30 menit sebelum kelas.
* Memastikan setiap student melakukan pengisian absensi.
* Memberikan sticky notes atau mengirimkan pesan melalui Slack/Zoom ketika ingin memberitahukan sesuatu kepada instructor.
* TA menjadi time keeper bagi instructor yang bertugas.
* Hari terakhir kelas, TA mengirimkan *assignment* quiz dan LBB pada google classroom.
* Hari terakhir kelas, teaching team memberikan link feedback kepada student. 

#### Kelas Online

* Melakukan pengecekan koneksi internet, kamera, dan audio dapat berjalan dengan baik. 
* Mengadakan sesi QnA selama 30 menit sebelum kelas.
* Memastikan recording dimulai sejak sesi QnA 30 menit sebelum kelas hingga kelas berakhir.
* Mengirimkan link absensi kepada student.
* Apabila student mengalami eror, maka TA mengarahkan student untuk mengirikan *screenshot* eror pada GDocs *Error Issues* yang sudah dipersiapkan.
* Setiap diadakan dive deeper, maka *teaching team* diperkenankan mengarahkan student untuk mengirimkan hasil pengerjaan dive deepernya pada GDocs yang sudah disediakan.
* Mengirimkan pesan melalui Slack/Zoom ketika ingin memberitahukan sesuatu kepada instructor.
* TA diperkenankan untuk membantu menjawab pertanyaan dari student yang dirasa bersifat umum.
* TA menjadi time keeper bagi instructor yang bertugas.
* Hari terakhir kelas, TA mengirimkan *assignment* quiz dan LBB pada google classroom.
* Hari terakhir kelas, teaching team memberikan link feedback kepada student. 

### Setelah Kelas

#### Kelas Onsite

* Membersihkan papan tulis dan area kelas.
* Mematikan AC dan lampu serta memastikan pintu telah dikunci.
* Mengirimkan inclass material yang telah diperbaharui dengan maksimal batas waktu sebagai berikut:

  + Kelas Day: pukul 10:00 WIB H+1 workshop
  + Kelas Night: pukul 13:00 WIB H+1 workshop

* Menginputkan nilai quiz pada google classroom dan [*score sheets*](https://docs.google.com/spreadsheets/d/1cGJ0pn9k9gKCBnceWVwaL9D7BBDMNjLh8uPYlaBlJi8/edit#gid=1518964141).
* Teaching team saling memberikan feedback dan input utnuk perbaikan kelas.

#### Kelas Online

* Mengirimkan recording kelas dengan maksimal batas waktu sebagai berikut:

  + Kelas Day: pukul 19:00 hari yang sama dengan workshop
  + Kelas Night: pukul 10:00 WIB H+1 workshop

* Mengirimkan inclass material yang telah diperbaharui dengan maksimal batas waktu sebagai berikut:

  + Kelas Day: pukul 10:00 WIB H+1 workshop
  + Kelas Night: pukul 13:00 WIB H+1 workshop
  
* Memberikan feedback dive deeper apabila ada.
* Menginputkan nilai quiz pada google classroom dan [*score sheets*](https://docs.google.com/spreadsheets/d/1cGJ0pn9k9gKCBnceWVwaL9D7BBDMNjLh8uPYlaBlJi8/edit#gid=1518964141).
* Teaching team saling memberikan feedback dan input utnuk perbaikan kelas.

> Dokumentasi fungsi untuk input nilai quiz dapat diakses pada link [github David](https://github.com/Davidlimbong/AlgoritmaAcademy)

## Quiz Guidelines
### Link Quiz

Berikut ini link quiz pada [corgi.re](corgi.re):

**Data Analytics Specialization**

* Python for Data Analytics (P4DA): [https://corgi.re/courses/ttnsy/quiz_PYW1](https://corgi.re/courses/ttnsy/quiz_PYW1)
* Exploratory Data Analysis (EDA): [https://corgi.re/courses/ttnsy/quiz_PYW2](https://corgi.re/courses/ttnsy/quiz_PYW2)
* Data Wrangling & Visualization (DWV): [https://corgi.re/courses/ttnsy/quiz_PYW3](https://corgi.re/courses/ttnsy/quiz_PYW3)
* SQL Query: [https://corgi.re/courses/ttnsy/quiz_PYW4](https://corgi.re/courses/ttnsy/quiz_PYW4)

**Data Visualization Specialization**

* Programming for Data Science - Practical Statistics (P4DS-PS): [https://corgi.re/courses/Davidlimbong/P4DS-PS](https://corgi.re/courses/Davidlimbong/P4DS-PS)
* Data Visualization (DV): [https://corgi.re/courses/Argaadya/Data-visualization](https://corgi.re/courses/Argaadya/Data-visualization)
* Interactive Plotting (IP): [https://corgi.re/courses/Davidlimbong/InteractivePlotting](https://corgi.re/courses/Davidlimbong/InteractivePlotting)

**Machine Learning Specialization**

* Programming for Data Science - Practical Statistics (P4DS-PS): [https://corgi.re/courses/Davidlimbong/P4DS-PS](https://corgi.re/courses/Davidlimbong/P4DS-PS)
* Regression Model (RM): [https://corgi.re/courses/ahmadhusain/regressionmodels](https://corgi.re/courses/ahmadhusain/regressionmodels)
* Classification in Machine Learning I (C1): [https://corgi.re/courses/inytss/classification1](https://corgi.re/courses/inytss/classification1)
* Classification in Machine Learning II (C2): [https://corgi.re/courses/ysitta/classification2](https://corgi.re/courses/ysitta/classification2)
* Unsupervised Learning (UL): [https://corgi.re/courses/Davidlimbong/UnsupervisedLearning](https://corgi.re/courses/Davidlimbong/UnsupervisedLearning)
* Time Series and Forecasting (TS): [https://corgi.re/courses/inytss/time-series](https://corgi.re/courses/inytss/time-series)
* Neural Network (NN): [https://corgi.re/courses/ysitta/neural_Network](https://corgi.re/courses/ysitta/neural_Network)

### Rubrik Quiz

* Setiap quiz memiliki penilaian biner, 0 untuk stduent yang tidak memenuhi nilai minimum dan bagi yang memenuhi nilai minimum akan memperoleh nilai penuh.

#### Data Analytics Specialization

Maksimal nilai setiap course:

* Python for Data Analytics (P4DA): 6
* Exploratory Data Analysis (EDA): 6
* Data Wrangling & Visualization (DWV): 6
* SQL Query: 6

#### Data Visualization Specialization

Maksimal nilai setiap course:

* Programming for Data Science - Practical Statistics (P4DS-PS): 4
* Data Visualization (DV): 2
* Interactive Plotting (IP): 1

#### Machine Learning Specialization

Maksimal nilai setiap course:

* Programming for Data Science - Practical Statistics (P4DS-PS): 4
* Regression Model (RM): 4
* Classification in Machine Learning I (C1): 4
* Classification in Machine Learning II (C2): 4
* Unsupervised Learning (UL): 4
* Time Series and Forecasting (TS): 4
* Neural Network (NN): 4

### Aturan Quiz

* *Assignment* quiz dikirimkan pada hari terakhir course melalui google classroom.
* Quiz dilakukan pada hari terakhir setiap course yang dilakukan secara serentak.
* Maksimal pengumpulan quiz setiap kelas sebagai berikut:

  + Kelas Day: pukul 19:00 WIB pada hari yang sama quiz diadakan
  + Kelas Night: pukul 09:00 WIB H+1 quiz diadakan

* Student tidak diperkenankan untuk mengerjakan quiz diluar waktu yang ditentukan.

### Quiz Susulan dan Perbaikan

* Student yang tidak dapat mengikuti quiz pada waktu yang telah ditentukan dapat mengikuti quiz susulan pada waktu yang akan ditentukan nantinya.
* Student yang tidak memenuhi nilai minimum quiz dapat mengikuti quiz remedial yang akan diadakan pada waktu yang sama dengan quiz susulan.
* Soal untuk quiz susulan dan remedial sama seperti quiz pada umumnya.
* Bagi student yang mengikuti kelas **Data Analytics Specialization** dapat melakukan perbaikan / susulan quiz dengan maksimal 2 course yang dapat dilakukan perbaikan / susulan.
* Bagi student yang mengikuti kelas **Data Visualization dan Machine Learning Specialization** dapat melakukan perbaikan / susulan quiz dengan maksimal 3 course yang dapat dilakukan perbaikan / susulan dari total course yang ada baik dalam Data Visualization Specialization maupun Machine Learning Specialization.
* Pelaksanaan quiz susulan dilakukan 3 hari setelah briefing Capstone Project dari setiap spesialisasi pada pukul 18.30 - 20:30 WIB.
* Nilai quiz akan diperbaharui melalui google classroom dan [sheet score](https://docs.google.com/spreadsheets/d/1cGJ0pn9k9gKCBnceWVwaL9D7BBDMNjLh8uPYlaBlJi8/edit#gid=1518964141) oleh PIC academy.

## Learn by Building (LBB) Guidelines
### Rubrik LBB

Detail rubrik masing-masing LBB pada **Data Visualization Specialization** dan **Machine Learning Specialization** dapat dilihat pada link [berikut](https://rpubs.com/AlgoritmaAcademy/lbb)

### Aturan LBB

* Rubrik LBB dikirimkan pada hari terakhir course bersamaan pengiriman *assignment* quiz.
* Student yang mengumpulkan LBB wajib menyertakan link publish LBB pada RPubs, Github, atau platform lainnya.
* Deadline pengumpulan LBB bagi student yang ingin mengikuti *career support* Algoritma dibagi menjadi 3 fase dengan detail sebagai berikut:

  + Fase 1: LBB course yang terdapat pada **Data Visualization Specialization** maksimal dikumpulkan sebelum Capstone Project Data Visualization.
  + Fase 2: LBB RM, C1, dan C2 maksimal dikumpulkan sebelum course TS dimulai.
  + Fase 3: LBB UL, TS, dan NN maksimal dikumpulkan 1 minggu setelah deadline Casptone Project Machine Learning.

* Student yang terlambat mengumpulkan LBB tidak mendapat pengurangan nilai kecuali LBB IP, keterlambatan akan dikenakan **pengurangan nilai 1 poin**.
* Student yang mengumpulkan LBB akan diberikan feedback oleh tim mentor maksimal 7 hari setelah LBB dikumpulkan melalui google classroom.
* Bagi student yang ingin mendapatkan career support **wajib** mengumpulkan LBB dengan detail banyaknya LBB yang harus dikumpulkan dapat dilihat pada **Chapter Data Career Day (DCD)**.

## Casptone Guidelines
### Rubrik Capstone

* Detail rubtik Capstone Project DA dapat diakses pada:

  + Auto Generated Email Based Report [link](https://github.com/ttnsy/fire-capstone)
  + Named Entity Recognition Service (API) [link](https://github.com/iqbalbasyar/ner-flask)
  + Flask Dashboard User Interface (UI) [link](https://github.com/fafilia/capstone-UIFlask)
  + Web Scraping using BeautifulSoup [link](https://github.com/t3981-h/BeautifulSoup-Capstone)
  
* Detail rubrik Capstone Project DV dapat diakses pada [link berikut](https://rpubs.com/AlgoritmaAcademy/dv-capstone).
* Detail rubrik Capstone Project ML dapat diakses pada [link berikut](https://rpubs.com/AlgoritmaAcademy/ml-capstone)

### Link Referensi Capstone
### Aturan Capstone

